# Learn the Alphabet

This is a simple sequence prediction problem that once understood can be generalized to other sequence prediction problems like time series prediction and sequence classification.

In [1]:
import numpy
from keras.models import Sequential
from keras.layers import Dense, LSTM
from keras.utils import np_utils

In [2]:
# fix random seed for reproducibility
numpy.random.seed(3)

In [3]:
# define the raw dataset
alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
# create mapping of characters to integers (0-25) and the reverse
char_to_int = dict((c,i) for i,c in enumerate(alphabet))
int_to_char = dict((i,c) for i,c in enumerate(alphabet))

In [4]:
char_to_int

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

In [5]:
# prepare the dataset of input to output pairs encoded as integers
seq_length = 1
dataX = []
dataY = []
for i in range(0,len(alphabet) - seq_length, 1):
    seq_in = alphabet[i:i+seq_length]
    seq_out = alphabet[i+seq_length]
    dataX.append([char_to_int[char] for char in seq_in])
    dataY.append(char_to_int[seq_out])
    print seq_in,'->',seq_out

A -> B
B -> C
C -> D
D -> E
E -> F
F -> G
G -> H
H -> I
I -> J
J -> K
K -> L
L -> M
M -> N
N -> O
O -> P
P -> Q
Q -> R
R -> S
S -> T
T -> U
U -> V
V -> W
W -> X
X -> Y
Y -> Z


In [6]:
# reshape X to be [samples, time steps, features]
X = numpy.reshape(dataX,(len(dataX),seq_length,1))

In [7]:
X

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[13]],

       [[14]],

       [[15]],

       [[16]],

       [[17]],

       [[18]],

       [[19]],

       [[20]],

       [[21]],

       [[22]],

       [[23]],

       [[24]]])

In [8]:
# normalize
X = X/float(len(alphabet))

In [9]:
X

array([[[ 0.        ]],

       [[ 0.03846154]],

       [[ 0.07692308]],

       [[ 0.11538462]],

       [[ 0.15384615]],

       [[ 0.19230769]],

       [[ 0.23076923]],

       [[ 0.26923077]],

       [[ 0.30769231]],

       [[ 0.34615385]],

       [[ 0.38461538]],

       [[ 0.42307692]],

       [[ 0.46153846]],

       [[ 0.5       ]],

       [[ 0.53846154]],

       [[ 0.57692308]],

       [[ 0.61538462]],

       [[ 0.65384615]],

       [[ 0.69230769]],

       [[ 0.73076923]],

       [[ 0.76923077]],

       [[ 0.80769231]],

       [[ 0.84615385]],

       [[ 0.88461538]],

       [[ 0.92307692]]])

In [10]:
# one hot encode the output variable
y = np_utils.to_categorical(dataY)

In [11]:
y

array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [15]:
# create and fit the model
model = Sequential()
model.add(LSTM(32, input_shape=(X.shape[1], X.shape[2])))
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy' ,optimizer='adam', metrics=['accuracy'])

In [16]:
model.fit(X,y,epochs=500,batch_size=1,verbose=2)

Epoch 1/500
1s - loss: 3.2649 - acc: 0.0400
Epoch 2/500
0s - loss: 3.2570 - acc: 0.0400
Epoch 3/500
0s - loss: 3.2544 - acc: 0.0400
Epoch 4/500
0s - loss: 3.2513 - acc: 0.0400
Epoch 5/500
0s - loss: 3.2489 - acc: 0.0400
Epoch 6/500
0s - loss: 3.2459 - acc: 0.0400
Epoch 7/500
0s - loss: 3.2427 - acc: 0.0800
Epoch 8/500
0s - loss: 3.2398 - acc: 0.0800
Epoch 9/500
0s - loss: 3.2371 - acc: 0.0800
Epoch 10/500
0s - loss: 3.2334 - acc: 0.0800
Epoch 11/500
0s - loss: 3.2297 - acc: 0.0800
Epoch 12/500
0s - loss: 3.2262 - acc: 0.0800
Epoch 13/500
0s - loss: 3.2225 - acc: 0.0800
Epoch 14/500
0s - loss: 3.2177 - acc: 0.0400
Epoch 15/500
0s - loss: 3.2133 - acc: 0.0800
Epoch 16/500
0s - loss: 3.2086 - acc: 0.0800
Epoch 17/500
0s - loss: 3.2041 - acc: 0.0400
Epoch 18/500
0s - loss: 3.1978 - acc: 0.0800
Epoch 19/500
0s - loss: 3.1919 - acc: 0.0800
Epoch 20/500
0s - loss: 3.1856 - acc: 0.0800
Epoch 21/500
0s - loss: 3.1793 - acc: 0.0800
Epoch 22/500
0s - loss: 3.1726 - acc: 0.0800
Epoch 23/500
0s - l

In [17]:
# summarize performance of the model
scores = model.evaluate(X, y, verbose=0)
print("Model Accuracy: %.2f%%" % (scores[1]*100))

Model Accuracy: 84.00%
