In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)
a

array([ 1.05746234,  1.18587024,  0.11601034,  0.12701802, -0.56271492])

In [5]:
a.shape

(5,)

In [6]:
a.T

array([ 1.05746234,  1.18587024,  0.11601034,  0.12701802, -0.56271492])

In [7]:
np.dot(a,a.T)

2.8707548683954958

In [8]:
b = np.random.randn(5,1)
b

array([[-0.60265446],
       [-0.44128935],
       [ 0.25240582],
       [ 0.88897193],
       [ 1.09417964]])

In [9]:
b.T

array([[-0.60265446, -0.44128935,  0.25240582,  0.88897193,  1.09417964]])

In [10]:
np.dot(b,b.T)

array([[ 0.3631924 ,  0.26594499, -0.1521135 , -0.5357429 , -0.65941224],
       [ 0.26594499,  0.19473629, -0.111384  , -0.39229384, -0.48284982],
       [-0.1521135 , -0.111384  ,  0.0637087 ,  0.22438169,  0.27617731],
       [-0.5357429 , -0.39229384,  0.22438169,  0.79027109,  0.97269498],
       [-0.65941224, -0.48284982,  0.27617731,  0.97269498,  1.19722907]])

In [11]:
assert(b.shape == (5,1))

In [12]:
a.reshape(5,1)

array([[ 1.05746234],
       [ 1.18587024],
       [ 0.11601034],
       [ 0.12701802],
       [-0.56271492]])