In [1]:
import numpy as np

a = np.array([1,2,3,4])

In [2]:
a

array([1, 2, 3, 4])

In [7]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

c

250151.39633005296

In [5]:
print 'vec version:'+str(1000*(toc-tic))+'ms'

vec version:1.49202346802ms


In [8]:
c= 0
tic = time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc = time.time()
print 'for loop:' + str(1000*(toc-tic))+'ms'

c

for loop:477.096796036ms


250151.39633005401

In [9]:
u = np.zeros((10,1))

In [10]:
u

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [11]:
np.exp
np.abs
np.maximum

<ufunc 'maximum'>

In [14]:
A = np.random.random([3,4])

In [15]:
A

array([[ 0.93745932,  0.20655021,  0.10190724,  0.80966844],
       [ 0.20092277,  0.02362359,  0.02937284,  0.01232809],
       [ 0.24806985,  0.07066229,  0.15130215,  0.37353378]])

In [16]:
cal = A.sum(axis=0)
cal


array([ 1.38645194,  0.30083609,  0.28258223,  1.19553031])

In [17]:
percentage = 100*A/cal.reshape(1,4)

In [18]:
percentage

array([[ 67.61570974,  68.6587199 ,  36.06286167,  67.72462672],
       [ 14.49186721,   7.85264512,  10.39444044,   1.03118137],
       [ 17.89242305,  23.48863498,  53.54269788,  31.24419191]])

In [24]:
cal.reshape(1,4)

array([[ 1.38645194,  0.30083609,  0.28258223,  1.19553031]])